### ISSUE TITLE
HTTPException: HTTP response '409: The operation was unsuccessful because a resource with that name already exists

### ISSUE THREAD

**Issue by chetanparekh** [NicholasAStuart/Maven-Mule-REST-Plugin#19]
I am getting following error while deploying application using Maven/mule-mmc-rest plugin 

[ERROR] Failed to execute goal com.github.nicholasastuart:mule-mmc-rest-plugin:1.2.0:deploy (mule-mmc-upload) on project project1: Error in attempting to deploy archive: org.apache.cxf.transport.http. HTTPException: HTTP response '409: The operation was unsuccessful because a resource with that name already exists.' when communicating with http://localhost:8585/mmc-3.7.0/api -> [Help 1]

http://forums.mulesoft.com/questions/38972/deployment-failing-while-deploying-using-mavenmule.html#answer-39109

Java Version : javac 1.8.0_45
OS : Microsoft Windows [Version 6.1.7601]
MMC: mmc-3.7.0
Mule: mule-enterprise-3.7.0

**Comment by NicholasAStuart** [comment]
@chetanparekh Did you get an answer or find a resolution?

**Comment by vfmunhoz** [comment]
Is there any fix for this problem?

**Comment by NicholasAStuart** [comment]
@vfmunhoz No, I just hadn't heard from him again, so I couldn't repro and closed it. Are you have this issue too? If so, can you post how I can reproduce this locally?

**Comment by vfmunhoz** [comment]
@NicholasAStuart yes i'm having this same issue.
I'm trying to understand what's happening, everything was working perfectly and suddenly the problem started.
There's more people deploying in the same server with this plugin and it's working for them, my guess is that this problem may be caused for something with my maven repo.
Anyway i'll keep you updated about this!
